services:
  semantic-kit-web:
    build: .
    ports:
      - "8080:80"
    container_name: semantic-kit-web
    restart: unless-stopped
    runtime: runc
    volumes:
      - ./assets:/usr/share/nginx/html/assets:ro
      - ./docs:/usr/share/nginx/html/docs:ro
      - ./protocols:/usr/share/nginx/html/protocols:ro
      - ./semantic_components:/usr/share/nginx/html/semantic_components:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
